#!/usr/bin/env bash
set -euo pipefail

# Usage:
#   ./generate_target_runtime_info.sh [output_header]
#
# Assumes CPU IDs are contiguous: cpu0, cpu1, ..., cpuN with no gaps.

OUTPUT_HEADER=${1:-target_runtime_info.h}

adb wait-for-device >/dev/null 2>&1
adb root >/dev/null 2>&1 || true

# Determine highest CPU index (assumes cpu0..cpuN)
max_cpu=$(adb shell "ls -d /sys/devices/system/cpu/cpu[0-9]* 2>/dev/null" \
           | sed 's/.*cpu//' \
           | sort -n \
           | tail -n1 \
           | tr -d '\r')

{
  echo "#pragma once"
  echo "#include <vector>"
  echo ""
  echo "// Auto-generated by generate_target_runtime_info.sh; do not edit."
  echo "// Frequencies are in kHz as reported by scaling_available_frequencies."
  echo ""
  echo "inline const std::vector<std::vector<int>> scaling_available_frequencies = {"
} > "$OUTPUT_HEADER"

for cpu in $(seq 0 "$max_cpu"); do
  freq_file="/sys/devices/system/cpu/cpu${cpu}/cpufreq/scaling_available_frequencies"

  # Read and normalize frequencies; if missing/empty, fail (since you assume no gaps)
  freqs=$(adb shell "cat $freq_file 2>/dev/null" \
            | tr -d '\r' \
            | tr '\n' ' ' \
            | tr -s '[:space:]' ' ' \
            | sed 's/^ *//' \
            | sed 's/ *$//')

  if [ -z "$freqs" ]; then
    echo "Error: missing or empty scaling_available_frequencies for cpu${cpu}" >&2
    exit 1
  fi

  freq_array=$(echo "$freqs" | tr ' ' ',')

  echo "    { $freq_array }," >> "$OUTPUT_HEADER"
done

echo "};" >> "$OUTPUT_HEADER"

echo "Generated $OUTPUT_HEADER (CPUs 0..$max_cpu)" >&2